package steps;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import io.cucumber.java.After;

public class TodoManagerSteps {
    private Response response;
    private String endpoint;
    private Process apiProcess;

    @Given("the Todo Manager API is running")
    public void apiRunning() {
        RestAssured.baseURI = "http://localhost:4567";
        if (!isApiRunning()) {
            startApi();
        } else {
            try {      
                given().when().get("/shutdown");
            } catch (Exception e) { } 
            try {
                Thread.sleep(200);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            startApi();
        }
    }

    private boolean isApiRunning() {
        try {
            URL url = new URL("http://localhost:4567/todos");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.connect();
            int responseCode = connection.getResponseCode();
            return responseCode == 200;
        } catch (IOException e) {
            return false;
        }
    }

    private void startApi() {
        try {
            apiProcess = new ProcessBuilder("java", "-jar", "runTodoManagerRestAPI-1.5.5.jar").start();
            Thread.sleep(200);
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Given("a project with the name {string} already exists")
    public void projectExists(String name) {
        endpoint = "/projects"; // Updating the endpoint variable
        String projectJson = "{\"title\": \"" + name + "\", \"description\": \"Autogenerated project\"}";
        given().contentType("application/json").body(projectJson).when().post(endpoint).then().statusCode(201);
    }

    @When("I send a POST request to {string} with name {string} and description {string}")
    public void postProject(String endpoint, String name, String description) {
        this.endpoint = endpoint;
        String projectJson = "{\"title\": \"" + name + "\", \"description\": \"" + description + "\"}";
        response = given().contentType("application/json").body(projectJson).when().post(this.endpoint);
    }

    @When("I send a POST request to {string} with ID {string} and name {string} and description {string}")
    public void postProjectWithId(String endpoint, String id, String name, String description) {
        String projectJson = "{\"id\": \"" + id + "\", \"title\": \"" + name + "\", \"description\": \"" + description + "\"}";
        response = given().contentType("application/json").body(projectJson).when().post(endpoint);
    }

    @When("I send a POST request to {string} without a name")
    public void postProjectWithoutName(String endpoint) {
        this.endpoint = endpoint;
        String projectJson = "{\"description\": \"Project without a name\"}";
        response = given().contentType("application/json").body(projectJson).when().post(this.endpoint);
    }

    @When("I send a GET request to {string}")
    public void sendGetRequest(String endpoint) {
        response = given().when().get(endpoint);
    }

    @When("I send a GET request to {string} with filter {string}")
    public void sendGetRequestWithFilter(String endpoint, String filter) {
        response = given().queryParam("title", filter).when().get(endpoint);
    }

    @When("I send a PUT request to {string} with ID {string}, new name {string} and description {string}")
    public void sendPutRequestWithIdNameAndDescription(String endpoint, String id, String newName, String description) {
        String projectJson = "{\"title\": \"" + newName + "\", \"description\": \"" + description + "\"}";
        response = given()
                       .contentType("application/json")
                       .body(projectJson)
                       .when()
                       .put("/projects/" + id);
    }    

    @When("I send a PUT request to {string} with ID {string} with active {string}")
    public void sendPutRequestWithActive(String endpoint, String id, String is_active) {
        String projectJson = "\"active\": \"" + is_active + "\"}";
        response = given()
                       .contentType("application/json")
                       .body(projectJson)
                       .when()
                       .put("/projects/" + id);
    }   
    
    @Then("I should receive a response with status code {int}")
    public void checkStatusCode(int statusCode) {
        response.then().statusCode(statusCode);
    }

    @Then("the response should contain a project with name {string} and description {string}")
    public void responseContainsProject(String name, String description) {
        response.then().body("title", equalTo(name)).body("description", equalTo(description));
    }

    @Then("the response should contain the error message {string}")
    public void responseShouldContainErrorMessage(String errorMessage) {
        String responseBody = response.asString();
        assertTrue(responseBody.contains(errorMessage));
    }

    @Then("the response should contain a project with name {string}")
    public void responseContainsProjectWithName(String expectedName) {
        String responseBody = response.asString();
        assertTrue(responseBody.contains(expectedName));
    }
}
